App\Request\UploadImageRequest:
  properties:
    uploadedFile:
      - Image:
          #mimeTypesMessage: "this id not message"
          maxSize: 2m
          maxSizeMessage: "Image size over 2M"

App\Request\CreateImageRequest:
  properties:
    image:
      - NotBlank: ~
    entity:
      - NotBlank: ~
    itemID:
      - NotBlank: ~

App\Request\UpdateImageRequest:
  properties:
    image:
      - NotBlank: ~

App\Request\UserRegisterRequest:
  properties:
    userID:
      - NotBlank: ~
    password:
      - NotBlank: ~

App\Request\UserProfileCreateRequest:
  properties:
    branch:
      - NotBlank: ~
    city:
      - NotBlank: ~
    phone:
      - NotBlank: ~

App\Request\UserProfileUpdateRequest:
  properties:
    id:
      - NotBlank: ~
    userID:
      - NotBlank: ~
    branch:
      - NotBlank: ~
    city:
      - NotBlank: ~
    phone:
      - NotBlank: ~
    bankName:
      - NotBlank: ~
    accountID:
      - NotBlank: ~
    stcPay:
      - NotBlank: ~

App\Request\userProfileUpdateByAdminRequest:
  properties:
    id:
      - NotBlank: ~
    status:
      - NotBlank: ~
    free:
      - NotBlank: ~

App\Request\CaptainProfileUpdateRequest:
  properties:
    captainName:
      - NotBlank: ~
    image:
      - NotBlank: ~
    age:
      - NotBlank: ~
    car:
      - NotBlank: ~
    drivingLicence:
      - NotBlank: ~

App\Request\CaptainProfileUpdateByAdminRequest:
  properties:
    captainID:
      - NotBlank: ~
    salary:
      - NotBlank: ~
    status:
      - NotBlank: ~
    bounce:
      - NotBlank: ~
      
App\Request\OrderUpdateRequest:
  properties:
    id:
      - NotBlank: ~
    destination:
      - NotBlank: ~
    payment:
      - NotBlank: ~

App\Request\AcceptedOrderCreateRequest:
  properties:
    orderID:
      - NotBlank: ~
    captainID:
      - NotBlank: ~

App\Request\AcceptedOrderUpdateRequest:
  properties:
    id:
      - NotBlank: ~
    orderID:
      - NotBlank: ~

App\Request\BankCreateRequest:
  properties:
    userID:
      - NotBlank: ~
    bankName:
      - NotBlank: ~
    accountID:
      - NotBlank: ~
    stcPay:
      - NotBlank: ~

App\Request\BankUpdateRequest:
  properties:
    bankName:
      - NotBlank: ~
    accountID:
      - NotBlank: ~
    stcPay:
      - NotBlank: ~

App\Request\ReportCreateRequest:
  properties:
    orderId:
      - NotBlank: ~
    reason:
      - NotBlank: ~

App\Request\BranchesDeleteRequest:
  properties:
    id:
      - NotBlank: ~
    isActive:
      - NotBlank: ~

App\Request\companyInfoCreateRequest:
  properties:
    phone:
      - NotBlank: ~

App\Request\companyInfoUpdateRequest:
  properties:
    id:
      - NotBlank: ~
    phone:
      - NotBlank: ~

App\Request\updateCreateRequest:
  properties:
    title:
      - NotBlank: ~
    content:
      - NotBlank: ~

App\Request\UpdateUpdateRequest:
  properties:
    id:
      - NotBlank: ~
    title:
      - NotBlank: ~
    content:
      - NotBlank: ~

App\Request\StoreProductCategoryLevelOneUpdateRequest:
  properties:
    productCategoryName:
      - NotBlank: ~
    productCategoryImage:
      - NotBlank: ~
    storeCategoryID:
      - NotBlank: ~

App\Request\StoreProductCategoryLevelTwoUpdateRequest:
  properties:
    productCategoryName:
      - NotBlank: ~
    productCategoryImage:
      - NotBlank: ~
    storeProductCategoryID:
      - NotBlank: ~

App\Request\ProductCreateRequest:
  properties:
    productName:
      - NotBlank: ~
    productImage:
      - NotBlank: ~
    productPrice:
      - NotBlank: ~
    storeProductCategoryID:
      - NotBlank: ~

App\Request\ProductUpdateByStoreOwnerRequest:
  properties:
    id:
      - NotBlank: ~
    productName:
      - NotBlank: ~
    productImage:
      - NotBlank: ~
    productPrice:
      - NotBlank: ~
    storeProductCategoryID:
      - NotBlank: ~

App\Request\ProductUpdateRequest:
  properties:
    id:
      - NotBlank: ~
    productName:
      - NotBlank: ~
    productImage:
      - NotBlank: ~
    productPrice:
      - NotBlank: ~
    storeProductCategoryID:
      - NotBlank: ~
    storeOwnerProfileID:
      - NotBlank: ~

App\Request\StoreCategoryCreateRequest:
  properties:
    storeCategoryName:
      - NotBlank: ~
    image:
      - NotBlank: ~

App\Request\StoreCategoryUpdateRequest:
  properties:
    id:
      - NotBlank: ~
    storeCategoryName:
      - NotBlank: ~

App\Request\StoreProductCategoryLevelTwoCreateRequest:
  properties:
    productCategoryName:
      - NotBlank: ~
    productCategoryImage:
      - NotBlank: ~
    storeProductCategoryID:
      - NotBlank: ~

App\Request\StoreProductCategoryCreateRequest:
  properties:
    productCategoryName:
      - NotBlank: ~
    productCategoryImage:
      - NotBlank: ~
    storeCategoryID:
      - NotBlank: ~

App\Request\AdminCreateRequest:
  properties:
    userID:
      - NotBlank: ~
    password:
      - NotBlank: ~

App\Request\CaptainTermCreateRequest:
  properties:
    content:
      - NotBlank: ~

App\Request\DeliveryCompanyFinancialCompensationCreateRequest:
  properties:
    kilometers:
      - NotBlank: ~
    maxKilometerBonus:
      - NotBlank: ~
    minKilometerBonus:
      - NotBlank: ~

App\Request\DeliveryCompanyFinancialRequest:
  properties:
    deliveryCost:
      - NotBlank: ~

App\Request\DeliveryCompanyFinancialUpdateRequest:
  properties:
    id:
      - NotBlank: ~
    deliveryCost:
      - NotBlank: ~

App\Request\DeliveryCompanyPaymentsFromCaptainCreateRequest:
  properties:
    captainId:
      - NotBlank: ~
    amount:
      - NotBlank: ~

App\Request\DeliveryCompanyPaymentsToCaptainCreateRequest:
  properties:
    captainId:
      - NotBlank: ~
    amount:
      - NotBlank: ~

App\Request\DeliveryCompanyPaymentsToStoreCreateRequest:
  properties:
    storeOwnerProfileID:
      - NotBlank: ~
    amount:
      - NotBlank: ~

App\Request\DeliveryCompanyInfoRequest:
  properties:
    phone:
      - NotBlank: ~

App\Request\RatingCreateRequest:
  properties:
    itemID:
      - NotBlank: ~
    rating:
      - NotBlank: ~
    orderNumber:
      - NotBlank: ~

App\Request\StoreOwnerBranchUpdateRequest:
  properties:
    id:
      - NotBlank: ~
    location:
      - NotBlank: ~

App\Request\StoreOwnerProfileUpdateRequest:
  properties:
    storeOwnerName:
      - NotBlank: ~
    image:
      - NotBlank: ~
    phone:
      - NotBlank: ~
    storeCategoryId:
      - NotBlank: ~
    privateOrders:
      - NotBlank: ~
    hasProducts:
      - NotBlank: ~
    location:
      - NotBlank: ~
    branchName:
      - NotBlank: ~
    openingTime:
      - NotBlank: ~
    closingTime:
      - NotBlank: ~

App\Request\StoreOwnerUpdateByAdminRequest:
  properties:
    id:
      - NotBlank: ~
    storeOwnerName:
      - NotBlank: ~
    status:
      - NotBlank: ~
#    is_best:
#      - NotBlank: ~
    image:
      - NotBlank: ~
    storeCategoryId:
      - NotBlank: ~
    privateOrders:
      - NotBlank: ~
    hasProducts:
      - NotBlank: ~
    openingTime:
      - NotBlank: ~
    closingTime:
      - NotBlank: ~

App\Request\storeOwnerProfileStatusUpdateByAdminRequest:
  properties:
    id:
      - NotBlank: ~
    status:
      - NotBlank: ~
